import Head from "next/head";
import Header from "../components/header";
import Splash from "../components/splash";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="flex-col">
      <Head>
        <title>Timer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/stopwatch.ico" />
      </Head>
      <Header />
      <Splash />
    </div>
  );
}
